version: '3'
services:
  api:
    build:
      context: .
      dockerfile: "Dockerfile"
    container_name: api_expense
    restart: always
    volumes:
      - ./:/usr/src/expense
    networks:
      - expense-network
    ports:
      - "8090:8090"
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    container_name: db_expense
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'expense_db'
    ports:
      - "25432:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    networks:
      - expense-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_expense
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - expense-network
networks:
  expense-network:
    driver: bridge
