version: '3'
services:
  authorization-server:
    build:
      context: ./expense-authorization-server
      dockerfile: "Dockerfile"
    container_name: expense_auth_server
    restart: always
    volumes:
      - ./expense-authorization-server:/usr/src/expense
    networks:
      - expense-network
    ports:
      - "8091:8091"
    depends_on:
      - db
  resoruce-server:
    build:
      context: ./expense-resoruce-server
      dockerfile: "Dockerfile"
    container_name: expense_resoruce_server
    restart: always
    volumes:
      - ./expense-resoruce-server:/usr/src/expense
    networks:
      - expense-network
    ports:
      - "8092:8092"
    depends_on:
      - db
      - authorization-server
  db:
    image: postgres:12.0-alpine
    container_name: db_expense
    restart: always
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'expense_db'
    ports:
      - "25432:5432"
    volumes:
      - "./expense-db-data:/var/lib/postgresql/data"
    networks:
      - expense-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_expense
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - expense-network
networks:
  expense-network:
    driver: bridge
